version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ci_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci_app
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
